# Generated by Django 3.1.7 on 2021-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20211011_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjobs',
            options={'verbose_name_plural': 'AppliedJobs'},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name_plural': 'CompanyDetails'},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'verbose_name_plural': 'JobPosition'},
        ),
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'verbose_name_plural': 'StudentDetails'},
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(help_text='Required. Inform a valid email address.', max_length=254, null=True),
        ),
    ]
