# Generated by Django 3.1.7 on 2021-10-12 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20211012_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='branch',
            field=models.CharField(choices=[('it', 'information_technology'), ('me', 'mech'), ('ce', 'civil'), ('eee', 'eee'), ('ece', 'ece'), ('ch', 'chemical'), ('cse', 'cse')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='cgpa_Btech',
            field=models.FloatField(help_text='*required', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='name',
            field=models.CharField(default='full name', help_text='*required', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='username',
            field=models.CharField(default='y1', help_text='enter username ex:y16it***', max_length=9, null=True),
        ),
    ]
